plugins:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
